/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.huihoo.social.service.base;

import com.huihoo.social.model.Socialcontent;
import com.huihoo.social.service.SocialcontentLocalService;
import com.huihoo.social.service.persistence.SocialcontentPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.search.Indexer;
import com.liferay.portal.kernel.search.IndexerRegistryUtil;
import com.liferay.portal.kernel.search.SearchException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the socialcontent local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.huihoo.social.service.impl.SocialcontentLocalServiceImpl}.
 * </p>
 *
 * @author Baihua Huang
 * @see com.huihoo.social.service.impl.SocialcontentLocalServiceImpl
 * @see com.huihoo.social.service.SocialcontentLocalServiceUtil
 * @generated
 */
public abstract class SocialcontentLocalServiceBaseImpl
	implements SocialcontentLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.huihoo.social.service.SocialcontentLocalServiceUtil} to access the socialcontent local service.
	 */

	/**
	 * Adds the socialcontent to the database. Also notifies the appropriate model listeners.
	 *
	 * @param socialcontent the socialcontent
	 * @return the socialcontent that was added
	 * @throws SystemException if a system exception occurred
	 */
	public Socialcontent addSocialcontent(Socialcontent socialcontent)
		throws SystemException {
		socialcontent.setNew(true);

		socialcontent = socialcontentPersistence.update(socialcontent, false);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(socialcontent);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return socialcontent;
	}

	/**
	 * Creates a new socialcontent with the primary key. Does not add the socialcontent to the database.
	 *
	 * @param id the primary key for the new socialcontent
	 * @return the new socialcontent
	 */
	public Socialcontent createSocialcontent(long id) {
		return socialcontentPersistence.create(id);
	}

	/**
	 * Deletes the socialcontent with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the socialcontent
	 * @throws PortalException if a socialcontent with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteSocialcontent(long id)
		throws PortalException, SystemException {
		Socialcontent socialcontent = socialcontentPersistence.remove(id);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(socialcontent);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Deletes the socialcontent from the database. Also notifies the appropriate model listeners.
	 *
	 * @param socialcontent the socialcontent
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteSocialcontent(Socialcontent socialcontent)
		throws SystemException {
		socialcontentPersistence.remove(socialcontent);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.delete(socialcontent);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return socialcontentPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return socialcontentPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return socialcontentPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return socialcontentPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public Socialcontent fetchSocialcontent(long id) throws SystemException {
		return socialcontentPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the socialcontent with the primary key.
	 *
	 * @param id the primary key of the socialcontent
	 * @return the socialcontent
	 * @throws PortalException if a socialcontent with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public Socialcontent getSocialcontent(long id)
		throws PortalException, SystemException {
		return socialcontentPersistence.findByPrimaryKey(id);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return socialcontentPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the socialcontents.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of socialcontents
	 * @param end the upper bound of the range of socialcontents (not inclusive)
	 * @return the range of socialcontents
	 * @throws SystemException if a system exception occurred
	 */
	public List<Socialcontent> getSocialcontents(int start, int end)
		throws SystemException {
		return socialcontentPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of socialcontents.
	 *
	 * @return the number of socialcontents
	 * @throws SystemException if a system exception occurred
	 */
	public int getSocialcontentsCount() throws SystemException {
		return socialcontentPersistence.countAll();
	}

	/**
	 * Updates the socialcontent in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param socialcontent the socialcontent
	 * @return the socialcontent that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public Socialcontent updateSocialcontent(Socialcontent socialcontent)
		throws SystemException {
		return updateSocialcontent(socialcontent, true);
	}

	/**
	 * Updates the socialcontent in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param socialcontent the socialcontent
	 * @param merge whether to merge the socialcontent with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the socialcontent that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public Socialcontent updateSocialcontent(Socialcontent socialcontent,
		boolean merge) throws SystemException {
		socialcontent.setNew(false);

		socialcontent = socialcontentPersistence.update(socialcontent, merge);

		Indexer indexer = IndexerRegistryUtil.getIndexer(getModelClassName());

		if (indexer != null) {
			try {
				indexer.reindex(socialcontent);
			}
			catch (SearchException se) {
				if (_log.isWarnEnabled()) {
					_log.warn(se, se);
				}
			}
		}

		return socialcontent;
	}

	/**
	 * Returns the socialcontent local service.
	 *
	 * @return the socialcontent local service
	 */
	public SocialcontentLocalService getSocialcontentLocalService() {
		return socialcontentLocalService;
	}

	/**
	 * Sets the socialcontent local service.
	 *
	 * @param socialcontentLocalService the socialcontent local service
	 */
	public void setSocialcontentLocalService(
		SocialcontentLocalService socialcontentLocalService) {
		this.socialcontentLocalService = socialcontentLocalService;
	}

	/**
	 * Returns the socialcontent persistence.
	 *
	 * @return the socialcontent persistence
	 */
	public SocialcontentPersistence getSocialcontentPersistence() {
		return socialcontentPersistence;
	}

	/**
	 * Sets the socialcontent persistence.
	 *
	 * @param socialcontentPersistence the socialcontent persistence
	 */
	public void setSocialcontentPersistence(
		SocialcontentPersistence socialcontentPersistence) {
		this.socialcontentPersistence = socialcontentPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.huihoo.social.model.Socialcontent",
			socialcontentLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.huihoo.social.model.Socialcontent");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	protected Class<?> getModelClass() {
		return Socialcontent.class;
	}

	protected String getModelClassName() {
		return Socialcontent.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = socialcontentPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = SocialcontentLocalService.class)
	protected SocialcontentLocalService socialcontentLocalService;
	@BeanReference(type = SocialcontentPersistence.class)
	protected SocialcontentPersistence socialcontentPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private static Log _log = LogFactoryUtil.getLog(SocialcontentLocalServiceBaseImpl.class);
	private String _beanIdentifier;
}