/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.huihoo.social.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Socialcontent service. Represents a row in the &quot;huihoo_app_socialcontent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.huihoo.social.model.impl.SocialcontentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.huihoo.social.model.impl.SocialcontentImpl}.
 * </p>
 *
 * @author Baihua Huang
 * @see Socialcontent
 * @see com.huihoo.social.model.impl.SocialcontentImpl
 * @see com.huihoo.social.model.impl.SocialcontentModelImpl
 * @generated
 */
public interface SocialcontentModel extends BaseModel<Socialcontent> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a socialcontent model instance should use the {@link Socialcontent} interface instead.
	 */

	/**
	 * Returns the primary key of this socialcontent.
	 *
	 * @return the primary key of this socialcontent
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this socialcontent.
	 *
	 * @param primaryKey the primary key of this socialcontent
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this socialcontent.
	 *
	 * @return the ID of this socialcontent
	 */
	public long getId();

	/**
	 * Sets the ID of this socialcontent.
	 *
	 * @param id the ID of this socialcontent
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this socialcontent.
	 *
	 * @return the user ID of this socialcontent
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this socialcontent.
	 *
	 * @param userId the user ID of this socialcontent
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this socialcontent.
	 *
	 * @return the user uuid of this socialcontent
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this socialcontent.
	 *
	 * @param userUuid the user uuid of this socialcontent
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the portrait url of this socialcontent.
	 *
	 * @return the portrait url of this socialcontent
	 */
	@AutoEscape
	public String getPortraitUrl();

	/**
	 * Sets the portrait url of this socialcontent.
	 *
	 * @param portraitUrl the portrait url of this socialcontent
	 */
	public void setPortraitUrl(String portraitUrl);

	/**
	 * Returns the screen name of this socialcontent.
	 *
	 * @return the screen name of this socialcontent
	 */
	@AutoEscape
	public String getScreenName();

	/**
	 * Sets the screen name of this socialcontent.
	 *
	 * @param screenName the screen name of this socialcontent
	 */
	public void setScreenName(String screenName);

	/**
	 * Returns the company ID of this socialcontent.
	 *
	 * @return the company ID of this socialcontent
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this socialcontent.
	 *
	 * @param companyId the company ID of this socialcontent
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this socialcontent.
	 *
	 * @return the group ID of this socialcontent
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this socialcontent.
	 *
	 * @param groupId the group ID of this socialcontent
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the type of this socialcontent.
	 *
	 * @return the type of this socialcontent
	 */
	public int getType();

	/**
	 * Sets the type of this socialcontent.
	 *
	 * @param type the type of this socialcontent
	 */
	public void setType(int type);

	/**
	 * Returns the content of this socialcontent.
	 *
	 * @return the content of this socialcontent
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this socialcontent.
	 *
	 * @param content the content of this socialcontent
	 */
	public void setContent(String content);

	/**
	 * Returns the created at of this socialcontent.
	 *
	 * @return the created at of this socialcontent
	 */
	public Date getCreatedAt();

	/**
	 * Sets the created at of this socialcontent.
	 *
	 * @param createdAt the created at of this socialcontent
	 */
	public void setCreatedAt(Date createdAt);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Socialcontent socialcontent);

	public int hashCode();

	public CacheModel<Socialcontent> toCacheModel();

	public Socialcontent toEscapedModel();

	public String toString();

	public String toXmlString();
}